image: node:20

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm ci

install_dependencies:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

build_project:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main
    - master
    - develop

pages:
  stage: deploy
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - main
    - master